openapi: 3.1.0
info:
  title: Custom Google Docs API
  version: 1.0.0
  description: API to authenticate, list Google Docs-compatible files, and read/update Google Docs using Flask.

servers:
  - url: https://df92-2407-d000-1a-e3-d573-b85e-9f94-f098.ngrok-free.app/
    description: Development server

paths:
  /startAuth:
    get:
      operationId: startAuth
      summary: Initiates Google OAuth flow
      description: Redirects the user to authenticate with Google.
      responses:
        "200":
          description: Authorization URL provided
          content:
            application/json:
              schema:
                type: object
                properties:
                  auth_url:
                    type: string
                    description: URL for user authentication

  /handleAuth:
    get:
      operationId: handleAuth
      summary: Handles Google OAuth redirect
      description: Processes the OAuth redirect and saves tokens.
      responses:
        "200":
          description: Authentication successful message
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Authentication successful!

  /listFiles:
    get:
      operationId: listFiles
      summary: List Google Docs-compatible files
      description: Fetches a list of files available in the user's Google Drive that are compatible with Google Docs.
      responses:
        "200":
          description: List of files
          content:
            application/json:
              schema:
                type: object
                properties:
                  files:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          description: File ID
                          example: "1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms"
                        name:
                          type: string
                          description: File name
                          example: "Sample Document"
                        mimeType:
                          type: string
                          description: MIME type of the file
                          example: "application/vnd.google-apps.document"

  /readDoc:
    get:
      operationId: readDoc
      summary: Read content from a Google Docs file
      description: Retrieves and returns the content of a Google Docs file specified by its `document_id`.
      parameters:
        - name: document_id
          in: query
          required: true
          description: The ID of the Google Docs file to read.
          schema:
            type: string
            example: "1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms"
      responses:
        "200":
          description: Content of the document
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: string
                    description: Text content of the document
                    example: "This is the content of the document."
        "400":
          description: Missing or invalid `document_id`
        "500":
          description: Internal server error

  /updateDoc:
    post:
      operationId: updateDoc
      summary: Update content in Google Docs
      description: Adds new content to a specific Google Docs file.
      requestBody:
        description: Details of the document and content to be added
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                document_id:
                  type: string
                  description: The ID of the Google Docs file
                  example: "1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms"
                content:
                  type: string
                  description: Text content to add
                  example: "New content for the document."
                location_index:
                  type: integer
                  description: Index in the document to insert content
                  example: 1
      responses:
        "200":
          description: Update successful message
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Content updated successfully in document: {document_id}"
        "400":
          description: Missing parameters
        "500":
          description: Internal server error
